site_name: LoRaChain
site_url: https://lorachain.github.io/

theme:
  name: material
  locale: en
  language: en

  palette:
    scheme: slate
    primary: blue
    accent: cyan

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top  


docs_dir: ./docs

extra:
  generator: false

markdown_extensions:
  - attr_list
  - md_in_html

repo_url: https://github.com/LoRaChain
repo_name: LoRaChain
edit_uri: Documents/tree/master/docs



